name = "shoppinglist-api"
main = "src/index.ts"
compatibility_date = "2023-03-21"

kv_namespaces = [
    { binding = "SHOPPINGLIST", id = "ec5f4345586346af8f1f5fd77d865e6d", preview_id = "b3f819d0400b485fb2eb68059cf9668e" },
]

d1_databases = [
    { binding = "DB", database_name = "shoppinglist_db", database_id = "f981eba6-bb61-4067-ac1e-af5014d4394c" },
]
