name = "shoppinglist-api"
main = "src/index.ts"
compatibility_date = "2023-03-21"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
    { binding = "SHOPPINGLIST", id = "ec5f4345586346af8f1f5fd77d865e6d", preview_id = "b3f819d0400b485fb2eb68059cf9668e" },
]

d1_databases = [
    { binding = "DB", database_name = "shoppinglist_db", database_id = "5a8f1785-e788-43ff-9f8c-4529cceee5b2" },
]
