name = "shoppinglist-api"
main = "src/index.ts"
compatibility_date = "2023-03-21"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "shoppinglist_db"
database_id = "f981eba6-bb61-4067-ac1e-af5014d4394c"
